use centro_estudantil;

DELIMITER //
CREATE PROCEDURE FINALIZAR_PERIODO_ESCOLAR()
BEGIN
    -- Corpo do procedimento
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE INICIAR_PERIODO_ESCOLAR()
BEGIN
    -- Corpo do procedimento
END //
DELIMITER ;